services:
  db:
    image: postgres:16-alpine
    container_name: local-postgres
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"             # 必要ならホスト側ポートは変更可
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      retries: 5

    volumes:
      - db-data:/var/lib/postgresql/data

  blog-app:
    build: .
    container_name: blog-app
    ports:
      - "8081:8080"   # ホスト:コンテナ
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/myapp?sslmode=disable
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
